### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [barbroldan/prj-rev-bwfs-dasmoto#3]
Meets expectations

Great job on this project it looks just like the  spec. I left a couple issues to help your code be a bit more semantic but this wouldn't change the look of your code. You did a great jobs using the right tags, adding comments, good spacing,  good job. Next, try to spice up the page, maybe add a background image for the header or some colors to the divs. Coolors.co has some cool schemes you can check out. Another idea is centering the image and text so it's not all left aligned

**Comment by barbroldan** [comment]
Appreciate your review and all the tips. Thanks!
